version: '3.7'

services:
  portal-compras-php:
    ports:
      - 9453:80
    image: registry.sistemas.cesan.com.br/adm/portal-compras-php:1.0.25
    env_file:
      - app-prd.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - uploads:/var/www/html/uploads
      - anexos:/var/www/html/anexos
    restart: always

volumes:
  uploads:
    driver_opts:
      type: "nfs"
      o: "addr=nfs-docker.sistemas.cesan.com.br,nolock,soft,rw"
      device: ":/nfs/dwp2/compras/uploads"
  anexos:
      driver_opts:
        type: "nfs"
        o: "addr=nfs-docker.sistemas.cesan.com.br,nolock,soft,rw"
        device: ":/nfs/dwp2/portal-de-compras/data/anexos"
