version: '3.7'

services:
  portal-compras-php:
    ports:
      - 9453:80
    image: registry.sistemas.cesan.com.br/adm/portal-compras-php:1.0.1
    env_file:
      - app-hom.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../html:/var/www/html
      - ../vendor:/var/www/vendor
      - ../TCPDF-main:/var/www/TCPDF-main
    restart: always
