version: '3.7'

services:
  portal-compras-php:
    volumes:
      - uploads:/var/www/html/uploads

volumes:
  uploads:
    driver_opts:
      type: "nfs"
      o: "addr=hom-nfs-docker.sistemas.cesan.com.br,nolock,soft,rw"
      device: ":/nfs/dwh2/portal-compras-php/uploads"
