version: '3.7'

services:
  portal-compras-php:
    ports:
      - 9453:80
    image: registry.sistemas.cesan.com.br/adm/portal-compras-php:1.0.22
    env_file:
      - app-hom.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - uploads:/var/www/html/uploads
    restart: always

volumes:
  uploads:
    driver_opts:
      type: "nfs"
      o: "addr=hom-nfs-docker.sistemas.cesan.com.br,nolock,soft,rw"
      device: ":/nfs/dwh2/portal-compras-php/uploads"

